[module]
[[module.imports]]
path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
[[module.imports]]
path = "github.com/FortAwesome/Font-Awesome"
[[module.imports.mounts]]
source = "scss"
target = "assets/scss/fontawesome"
[[module.imports.mounts]]
source = "webfonts"
target = "static/fonts"
[[module.imports]]
path = "github.com/source-foundry/Hack"
[[module.imports.mounts]]
source = "build/web/"
target = "static/css/hack"
[[module.imports.mounts]]
source = "build/web/fonts"
target = "static/fonts"
