baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Pizzeria'

[module]
  [[module.imports]]
    path = "github.com/xvalcarce/pizzeria"


[params]
  headerName = "taglio·pizza"
  headerSubtitle = "Una storia di passione e tradizione"
  logo = "images/logo.svg"
  logoHoover = "images/logoHoover.svg"
  [[params.social]]
	icon = "fab fa-github fa-1x"
    url = "https://github.com/xvalcarce"
  [[params.social]]
    icon = "fab fa-twitter fa-1x"
	url = "https://twitter.com/Plut0n_"
  [[params.social]]
  	icon = "fab fa-google-scholar fa-1x"
	url = "https://scholar.google.com/citations?user=OULhh8IAAAAJ"
		
  [params.style]
    flavor = "mocha" # latte, frappe, macchiato or mocha


[menus]
  # This is the menu appearing in the header below the headerName
  [[menus.main]]
    name = 'Secrets'
    pageRef = '/posts'
    weight = 1
  [[menus.main]]
    name = 'Pizzas'
    pageRef = '/pizzas'
    weight = 2
  [[menus.main]]
    name = 'About'
    pageRef = '/about'
		weight = 3
