baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Pizzeria'

[module]
  [[module.imports]]
    path = "github.com/xvalcarce/pizzeria"

[params]
  headerName = "taglio·pizza"
  headerSubtitle = "Una storia di passione e tradizione"
  [[params.social]]
	icon = "fab fa-github fa-1x"
    url = "https://github.com/xvalcarce"
  [[params.social]]
    icon = "fab fa-twitter fa-1x"
	url = "https://twitter.com/Plut0n_"
  [[params.social]]
  	icon = "fab fa-google-scholar fa-1x"
	url = "https://scholar.google.com/citations?user=OULhh8IAAAAJ"
		
  [params.style]
    flavor = "frappe" # latte, frappe, macchiato or mocha
